import { createActions } from "redux-actions";

export const {
  updateIdToken,
  setAuthData,
  setUser,
  signInUser,
  logOut,
  logOuting,
  initialAuth,
  deleteAuthData,
  authenticate,
  authenticationRequested,
  authenticationSucceeded,
  authenticationFailed,
  authenticationSkipped,
  takeFreeWorkoutCompleted,
  updateWeight,
  updateCustomerAttribute,
  sessionIn,
  sessionOut,
} = createActions(
  "UPDATE_ID_TOKEN",
  "SET_AUTH_DATA",
  "SET_USER",
  "SIGN_IN_USER",
  "LOG_OUT",
  "LOG_OUTING",
  "INITIAL_AUTH",
  "DELETE_AUTH_DATA",
  "AUTHENTICATE",
  "AUTHENTICATION_REQUESTED",
  "AUTHENTICATION_SUCCEEDED",
  "AUTHENTICATION_FAILED",
  "AUTHENTICATION_SKIPPED",
  "TAKE_FREE_WORKOUT_COMPLETED",
  "UPDATE_WEIGHT",
  "UPDATE_CUSTOMER_ATTRIBUTE",
  "SESSION_IN",
  "SESSION_OUT",
  { prefix: "AUTH" }
);
