import { createActions } from "redux-actions";

export const {
  payWithNmi,
  payWithPayPal,
  canceledPayPal,
  errorPayPal,
  payWithStripe,
  paymentRequested,
  paymentSucceeded,
  paymentFailed,
  paymentCanceled,
  setIdempotencyKey,
  setStripeIntent,
  clearStripeIntent,
  checkoutInitial,
  checkPaymentMode,
  setPaymentMode,
  setChangePlan,
  clearChangePlan,
  setPayPalPlanId,
  setKeyValue,
  changePaymentProvider,
  changeVoucher,
  sendSubscription,
  reactivateSubscription,
  inside,
  outside,
  validCartId
} = createActions(
  "PAY_WITH_NMI",
  "PAY_WITH_PAY_PAL",
  "CANCELED_PAY_PAL",
  "ERROR_PAY_PAL",
  "PAY_WITH_STRIPE",
  "PAYMENT_REQUESTED",
  "PAYMENT_SUCCEEDED",
  "PAYMENT_FAILED",
  "PAYMENT_CANCELED",
  "SET_IDEMPOTENCY_KEY",
  "SET_STRIPE_INTENT",
  "CLEAR_STRIPE_INTENT",
  "CHECKOUT_INITIAL",
  "CHECK_PAYMENT_MODE",
  "SET_PAYMENT_MODE",
  "SET_CHANGE_PLAN",
  "CLEAR_CHANGE_PLAN",
  "SET_PAYPAL_PLANID",
  "SET_KEY_VALUE",
  "CHANGE_PAYMENT_PROVIDER",
  "CHANGE_VOUCHER",
  "SEND_SUBSCRIPTION",
  "REACTIVATE_SUBSCRIPTION",
  "INSIDE",
  "OUTSIDE",
  "VALID_CART_ID",
  { prefix: "CHECKOUT" }
);
